### ISSUE TITLE
Allow queued resignation after round end

### ISSUE THREAD

**Issue by bartbes** [grifferz/pah-irc#151] opened 2015-05-02 19:27 UTC
It would be nice if I could resign after having played a card, if the resignation only happened after the round had ended. Since it requires no more activity from the player onwards, they could still earn a point by leaving a slow round that way.

**Comment by grifferz** [comment] 2015-05-02 21:26
Duplicate of #91.

**Closed as completed by grifferz** 2015-05-02 21:26 UTC
Labels: enhancement
