### ISSUE TITLE
Missing explanation when card Tsar is forcibly resigned, same Tsar is kept

### ISSUE THREAD

**Issue by domcleal** [grifferz/pah-irc#86] opened 2015-03-01 10:07 UTC
When the Tsar is forcibly resigned, there should be a message to the channel and private messages to indicate to players that they need to re-play the round (though #25 may also alleviate the need for this).

**Comment by grifferz** [comment] 2015-03-01 18:49
It seems to be because, while compressing end-of-round messages, I left it so that `pick_new_tsar` could try to announce the winner for a round that had no winner, and thus met an exception and didn't complete.

This accounts for both why there were no end of round messages and why the Tsar has not been moved on, so #85 is a duplicate of this one.

**Closed as completed** 2015-03-01 19:46 UTC
Labels: bug
