### ISSUE TITLE
When announcing new White Card, give number as well

### ISSUE THREAD

**Issue by zuzak** [grifferz/pah-irc#72] opened 2015-02-22 16:18 UTC
At the moment, I have to ask the bot to `hand` each time, because I don't know the numbers of the cards I was just dealt. It'd be nice for the bot to tell me when it deals, so I can just look at the scrollback instead of issuing `hand` yet again; e.g.

```
16:11:45 <PAH> 1 new White Card has been dealt to you in #debug:
16:11:46 <PAH> 6. Shiny objects.
16:11:47 <PAH> To see your full hand, type "hand".
```

**Comment by grifferz** [comment] 2015-02-22 16:28
Duplicate of #4.

**Closed as completed by grifferz** 2015-02-22 16:28 UTC
